name: Build and Run Eigen nbody

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      run: |
        lscpu && free -h && df -h

    - name: Run build script
      run: |
        bash projects/duckdb_null_value/run.sh
